train: /home/exouser/Desktop/idp_codebase/datasets/yolo11/ipd_bop_data_jan25_1_obj_11/images
val: /home/exouser/Desktop/idp_codebase/datasets/yolo11/ipd_bop_data_jan25_1_obj_11/images
nc: 1
names: ['object_11']
